apiVersion: v1
kind: Service
metadata:
  name: {{ include "dashy.fullname" . }}
spec:
  type: {{ .Values.dashy.service.type }}
  ports:
    - port: {{ .Values.dashy.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "dashy.name" . }}
