apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  type: {{ .Values.homeassistant.service.type }}
  ports:
    - port: {{ .Values.homeassistant.service.port }}
      targetPort: 8123
      protocol: TCP
      name: http
  selector:
    app: homeassistant
