apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ssh://git@gitea-ssh.gitea.svc.cluster.local:2222/pandatrax/gitops-platform.git'
    targetRevision: main
    path: apps/metallb/config
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  dependsOn:
    - metallb-helm