apiVersion: v1
kind: Service
metadata:
  name: zwavejs
  namespace: homeassistant
spec:
  type: ExternalName
  externalName: zwavejs.tail646b2.ts.net
  ports:
    - name: websocket
      port: 3000       # Port Home Assistant will connect to
      protocol: TCP
